name: droplet
description: HCI group project
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  dynamic_theme: ^1.0.1
  eva_icons_flutter: ^2.0.0
  flare_flutter: ^2.0.1
  gradient_widgets: ^0.5.2
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: 'launcher_icon'
  image_path_android: 'assets/icon/icon-legacy.png'
  adaptive_icon_foreground: 'assets/icon/icon-adaptive.png'
  adaptive_icon_background: '#fafafa'

  ios: true
  image_path_ios: 'assets/icon/icon-ios.png'

flutter:
  uses-material-design: true

  assets:
     - assets/cards/facts/
     - assets/cards/story/
     - assets/credits/
     - assets/icon/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen/Sen-Regular.ttf
        - asset: assets/fonts/Sen/Sen-Bold.ttf